'use strict';

import fs from 'fs';
import path from 'path';

/**
 * ReportGenerator — Creates a JSON report and dashboard data file
 * from the exploration results.
 */
class ReportGenerator {
  graph: any;
  bugs: any[];
  stats: any;

  /**
   * @param {import('./state-graph').StateGraph} stateGraph - Explored state graph
   * @param {Array} bugs - Array of discovered bugs
   * @param {object} stats - Exploration statistics
   */
  constructor(stateGraph, bugs, stats) {
    this.graph = stateGraph;
    this.bugs = bugs;
    this.stats = stats;
  }

  /**
   * Generate the full JSON report.
   * @param {string} outputPath - Path to write report.json
   */
  generateJSON(outputPath) {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const report = {
      timestamp: new Date().toISOString(),
      targetUrl: this.stats.startUrl || 'http://localhost:5173',
      stats: {
        totalStates: this.stats.statesDiscovered || 0,
        totalTransitions: this.stats.transitionsFound || 0,
        totalBugs: this.bugs.length,
        explorationDepth: this.stats.depthReached || 0,
        duration: this.stats.duration || 0,
        actionsAttempted: this.stats.actionsAttempted || 0,
        errorsEncountered: this.stats.errorsEncountered || 0
      },
      bugs: this.bugs.map(bug => this._serializeBug(bug)),
      graph: this._serializeGraph()
    };

    fs.writeFileSync(outputPath, JSON.stringify(report, null, 2), 'utf-8');
    
    // Generate CI/CD related outputs
    this._generatePRSummary(path.join(dir, 'pr-summary.md'), report);
    this._generateMachineReadableResults(path.join(dir, 'simtest-results.json'), report);

    return outputPath;
  }

  /**
   * Generate a markdown PR summary.
   * @param {string} outputPath - Path to write pr-summary.md
   * @param {object} report - The full JSON report object
   */
  _generatePRSummary(outputPath, report) {
    const lines = [];
    lines.push('## SimTest Results');
    lines.push('');
    lines.push(`- **States Discovered:** ${report.stats.totalStates}`);
    lines.push(`- **Transitions Found:** ${report.stats.totalTransitions}`);
    lines.push(`- **Bugs Found:** ${report.stats.totalBugs}`);
    lines.push(`- **Duration:** ${this._formatDuration(report.stats.duration)}`);
    lines.push('');
    
    if (report.bugs.length === 0) {
      lines.push('✅ No bugs found! Great job.');
    } else {
      lines.push('### 🐛 Bugs Found');
      report.bugs.forEach(bug => {
        const url = (bug.state && bug.state.url) ? bug.state.url : 'unknown';
        lines.push(`- **${bug.severity.toUpperCase()}**: ${bug.type} - ${bug.description} (at \`${url}\`)`);
      });
    }
    
    fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
  }

  /**
   * Generate simplified machine-readable results.
   * @param {string} outputPath - Path to write simtest-results.json
   * @param {object} report - The full JSON report object
   */
  _generateMachineReadableResults(outputPath, report) {
    const results = {
      success: report.bugs.filter(b => b.severity === 'high').length === 0,
      totalBugs: report.stats.totalBugs,
      highSeverityBugs: report.bugs.filter(b => b.severity === 'high').length,
      mediumSeverityBugs: report.bugs.filter(b => b.severity === 'medium').length,
      lowSeverityBugs: report.bugs.filter(b => b.severity === 'low').length,
      states: report.stats.totalStates,
      duration: report.stats.duration
    };
    fs.writeFileSync(outputPath, JSON.stringify(results, null, 2), 'utf-8');
  }

  /**
   * Generate dashboard-data.js that can be loaded by the HTML dashboard.
   * @param {string} outputPath - Path to write dashboard-data.js
   */
  generateDashboardData(outputPath) {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const data = {
      timestamp: new Date().toISOString(),
      targetUrl: this.stats.startUrl || 'http://localhost:5173',
      stats: {
        totalStates: this.stats.statesDiscovered || 0,
        totalTransitions: this.stats.transitionsFound || 0,
        totalBugs: this.bugs.length,
        explorationDepth: this.stats.depthReached || 0,
        duration: this.stats.duration || 0
      },
      bugs: this.bugs.map(bug => this._serializeBug(bug)),
      graph: this._serializeGraph()
    };

    const jsContent = `// Auto-generated by SimTest — ${new Date().toISOString()}
// This file is loaded by the SimTest dashboard
window.SIMTEST_DATA = ${JSON.stringify(data, null, 2)};
`;

    fs.writeFileSync(outputPath, jsContent, 'utf-8');
    return outputPath;
  }

  /**
   * Serialize a bug object for the report (remove Buffer screenshots).
   * @param {object} bug - Bug object
   * @returns {object} Serializable bug
   */
  _serializeBug(bug) {
    return {
      id: bug.id,
      severity: bug.severity,
      type: bug.type,
      description: bug.description,
      state: {
        url: bug.state ? bug.state.url : null,
        title: bug.state ? bug.state.title : null,
        timestamp: bug.state ? bug.state.timestamp : null
      },
      action: bug.action ? {
        type: bug.action.type,
        selector: bug.action.selector,
        value: bug.action.value,
        description: bug.action.description
      } : null,
      evidence: {
        errors: bug.evidence ? bug.evidence.errors : [],
        // Convert screenshot Buffer to base64 if present
        screenshot: (bug.evidence && bug.evidence.screenshot && Buffer.isBuffer(bug.evidence.screenshot))
          ? bug.evidence.screenshot.toString('base64')
          : null
      },
      timestamp: bug.timestamp || Date.now()
    };
  }

  /**
   * Serialize the state graph for visualization.
   * @returns {{nodes: Array, edges: Array}} Graph data for vis-network
   */
  _serializeGraph() {
    const graphData = this.graph.serialize();
    const bugStateUrls = new Set(this.bugs.map(b => b.state?.url).filter(Boolean));

    const nodes = [];
    const edges = [];

    if (graphData.nodes) {
      for (const node of graphData.nodes) {
        const stateData = (node.label && node.label.stateData) ? node.label.stateData : {};
        const url = stateData.url || '';
        const urlPath = this._extractPath(url);

        nodes.push({
          id: node.id,
          label: urlPath || (node.id ? node.id.slice(0, 8) : 'unknown'),
          url: url,
          explored: (node.label && node.label.explored) || false,
          hasBug: bugStateUrls.has(url)
        });
      }
    }

    if (graphData.edges) {
      for (const edge of graphData.edges) {
        const action = (edge.label && edge.label.action) ? edge.label.action : {};
        edges.push({
          from: edge.from,
          to: edge.to,
          action: action.description || `${action.type || 'unknown'} ${action.selector || ''}`
        });
      }
    }

    return { nodes, edges };
  }

  /**
   * Extract URL pathname for display.
   * @param {string} url - Full URL
   * @returns {string} Pathname
   */
  _extractPath(url) {
    try {
      return new URL(url).pathname;
    } catch {
      return url;
    }
  }

  /**
   * Print a summary to the console.
   * @returns {string} Summary text
   */
  getSummary() {
    const lines = [];
    lines.push('');
    lines.push('═══════════════════════════════════════');
    lines.push('       SimTest Exploration Report');
    lines.push('═══════════════════════════════════════');
    lines.push('');
    lines.push(`States Discovered:  ${this.stats.statesDiscovered || 0}`);
    lines.push(`Transitions Found:  ${this.stats.transitionsFound || 0}`);
    lines.push(`Actions Attempted:  ${this.stats.actionsAttempted || 0}`);
    lines.push(`Exploration Depth:  ${this.stats.depthReached || 0}`);
    lines.push(`Duration:           ${this._formatDuration(this.stats.duration || 0)}`);
    lines.push('');
    lines.push(`Bugs Found:         ${this.bugs.length}`);

    const high = this.bugs.filter(b => b.severity === 'high').length;
    const medium = this.bugs.filter(b => b.severity === 'medium').length;
    const low = this.bugs.filter(b => b.severity === 'low').length;

    if (high > 0) lines.push(`  🔴 High:    ${high}`);
    if (medium > 0) lines.push(`  🟡 Medium:  ${medium}`);
    if (low > 0) lines.push(`  🟢 Low:     ${low}`);

    lines.push('');
    lines.push('═══════════════════════════════════════');

    return lines.join('\n');
  }

  /**
   * Format milliseconds to a human-readable duration.
   * @param {number} ms - Duration in milliseconds
   * @returns {string} Formatted duration
   */
  _formatDuration(ms) {
    if (ms < 1000) return `${ms}ms`;
    const seconds = Math.floor(ms / 1000);
    if (seconds < 60) return `${seconds}s`;
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}m ${remainingSeconds}s`;
  }
}

export {  ReportGenerator  };
