'use strict';

import fs from 'fs';
import path from 'path';

/**
 * TestGenerator — Converts discovered bugs into runnable Playwright Test files.
 *
 * For each bug, uses the state graph's shortest path from initial state
 * to the bug state to generate minimal reproduction steps.
 */
class TestGenerator {
  graph;
  outputDir;

  /**
   * @param {import('./state-graph').StateGraph} stateGraph - The explored state graph
   * @param {string} outputDir - Directory to write generated tests
   */
  constructor(stateGraph, outputDir) {
    this.graph = stateGraph;
    this.outputDir = outputDir;
  }

  /**
   * Generate test files for all provided bugs.
   * @param {Array} bugs - Array of bug objects from BugFinder
   * @returns {Array<string>} Paths to generated test files
   */
  generateAll(bugs) {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }

    const generatedFiles = [];
    for (const bug of bugs) {
      try {
        const filePath = this.generateTest(bug);
        if (filePath) {
          generatedFiles.push(filePath);
        }
      } catch (error) {
        console.error(`Failed to generate test for ${bug.id}: ${error.message}`);
      }
    }

    // Generate playwright.config.js for the test suite
    this._generateConfig();

    return generatedFiles;
  }

  /**
   * Generate a single Playwright test file for a bug.
   * @param {object} bug - Bug object
   * @returns {string|null} Path to generated file
   */
  generateTest(bug) {
    const safeName = this._sanitizeFilename(bug.id, bug.type, bug.description);
    const fileName = `${safeName}.spec.js`;
    const filePath = path.join(this.outputDir, fileName);

    // Get reproduction path from graph
    const reproSteps = this._getReproductionSteps(bug);
    const testCode = this._buildTestCode(bug, reproSteps);

    fs.writeFileSync(filePath, testCode, 'utf-8');
    return filePath;
  }

  /**
   * Get the reproduction steps from root to bug state.
   * @param {object} bug - Bug object
   * @returns {Array} Ordered steps to reproduce
   */
  _getReproductionSteps(bug) {
    const steps = [];

    if (bug.reproducePath && bug.reproducePath.length > 0) {
      // Use the stored reproduction path
      for (const step of bug.reproducePath) {
        if (step.action) {
          steps.push({
            type: step.action.type || 'navigate',
            selector: step.action.selector,
            value: step.action.value,
            url: step.url,
            description: step.action.description || `${step.action.type} ${step.action.selector}`
          });
        } else if (step.url) {
          steps.push({
            type: 'navigate',
            url: step.url,
            description: `Navigate to ${step.url}`
          });
        }
      }
    }

    // Always include the final action that triggered the bug
    if (bug.action && bug.action.selector) {
      steps.push({
        type: bug.action.type || 'click',
        selector: bug.action.selector,
        value: bug.action.value,
        description: `${bug.action.type} ${bug.action.selector} (triggers bug)`
      });
    }

    return steps;
  }

  /**
   * Build the Playwright test code string.
   * @param {object} bug - Bug object
   * @param {Array} steps - Reproduction steps
   * @returns {string} Complete test file content
   */
  _buildTestCode(bug, steps) {
    const lines = [];

    // Header comment
    lines.push(`// Auto-generated by SimTest — ${new Date().toISOString()}`);
    lines.push(`// ${bug.id}: ${bug.description}`);
    lines.push(`// Severity: ${bug.severity}`);
    lines.push(`// Type: ${bug.type}`);
    lines.push('');
    lines.push("import {  test, expect  } from '@playwright/test';");
    lines.push('');

    // Test function
    const testName = `${bug.id}: ${bug.description}`;
    lines.push(`test('${this._escapeString(testName)}', async ({ page }) => {`);

    // Navigate to the bug state URL first
    const stateUrl = bug.state && bug.state.url ? bug.state.url : 'http://localhost:5173';
    lines.push(`  // Navigate to target page`);
    lines.push(`  await page.goto('${this._escapeString(stateUrl)}');`);
    lines.push('');

    // Reproduction steps
    if (steps.length > 0) {
      lines.push('  // Reproduction steps');
      for (let i = 0; i < steps.length; i++) {
        const step = steps[i];
        lines.push(`  // Step ${i + 1}: ${step.description}`);
        lines.push(this._stepToPlaywrightCode(step));
        lines.push('  await page.waitForTimeout(500);');
        lines.push('');
      }
    }

    // Assertion based on bug type
    lines.push('  // Assertion');
    lines.push(this._getAssertion(bug));
    lines.push('});');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Convert a reproduction step to Playwright code.
   * @param {object} step - Step object
   * @returns {string} Playwright code line
   */
  _stepToPlaywrightCode(step) {
    switch (step.type) {
      case 'click':
        return `  await page.click('${this._escapeString(step.selector)}');`;

      case 'fill':
        return `  await page.fill('${this._escapeString(step.selector)}', '${this._escapeString(step.value || '')}');`;

      case 'select':
        return `  await page.selectOption('${this._escapeString(step.selector)}', '${this._escapeString(step.value || '')}');`;

      case 'check':
        return `  await page.check('${this._escapeString(step.selector)}');`;

      case 'navigate':
        return `  await page.goto('${this._escapeString(step.url || step.selector)}');`;

      default:
        return `  // Unknown action type: ${step.type}`;
    }
  }

  /**
   * Generate assertion code based on bug type.
   * @param {object} bug - Bug object
   * @returns {string} Assertion code
   */
  _getAssertion(bug) {
    switch (bug.type) {
      case 'js_crash':
        return [
          '  // Verify no JavaScript errors on page',
          '  const errors = [];',
          "  page.on('pageerror', e => errors.push(e.message));",
          '  await page.waitForTimeout(1000);',
          '  expect(errors).toHaveLength(0);'
        ].join('\n');

      case 'nan_in_ui':
        return [
          "  // Verify page doesn't contain NaN",
          "  const bodyText = await page.textContent('body');",
          "  expect(bodyText).not.toContain('NaN');"
        ].join('\n');

      case 'network_error':
        return [
          '  // Verify no server errors',
          '  const failedResponses = [];',
          "  page.on('response', r => { if (r.status() >= 500) failedResponses.push(r.url()); });",
          '  await page.waitForTimeout(2000);',
          '  expect(failedResponses).toHaveLength(0);'
        ].join('\n');

      case 'dead_end':
        return [
          '  // Verify page has interactive elements (not a dead end)',
          "  const buttons = await page.locator('a, button, input, [role=\"button\"]').all();",
          '  const visible = [];',
          '  for (const b of buttons) {',
          '    if (await b.isVisible()) visible.push(b);',
          '  }',
          '  expect(visible.length).toBeGreaterThan(0);'
        ].join('\n');

      case 'console_error':
        return [
          '  // Verify no console errors',
          '  const consoleErrors = [];',
          "  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });",
          '  await page.waitForTimeout(1000);',
          '  expect(consoleErrors).toHaveLength(0);'
        ].join('\n');

      case 'unprotected_route':
        return [
          '  // Verify protected route redirects unauthenticated users',
          "  // If we can access this page without login, it's a bug",
          '  const url = page.url();',
          "  expect(url).toContain('/login');"
        ].join('\n');

      default:
        return [
          '  // Generic assertion — page should be in a valid state',
          "  const bodyText = await page.textContent('body');",
          "  expect(bodyText).not.toContain('NaN');",
          "  expect(bodyText).not.toContain('undefined');"
        ].join('\n');
    }
  }

  /**
   * Generate a playwright.config.js file for the test suite.
   */
  _generateConfig() {
    const config = `// Auto-generated by SimTest
import {  defineConfig  } from '@playwright/test';

export default defineConfig;({
  testDir: './',
  timeout: 30000,
  retries: 0,
  use: {
    baseURL: 'http://localhost:5173',
    headless: true,
    screenshot: 'on',
    trace: 'on-first-retry',
  },
  reporter: [['html', { open: 'never' }]],
});
`;
    const configPath = path.join(this.outputDir, 'playwright.config.js');
    fs.writeFileSync(configPath, config, 'utf-8');
  }

  /**
   * Sanitize a bug into a valid filename.
   * @param {string} id - Bug ID
   * @param {string} type - Bug type
   * @param {string} description - Bug description
   * @returns {string} Safe filename (without extension)
   */
  _sanitizeFilename(id, type, description) {
    const base = `${id}-${type}`;
    const safe = base
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60);
    return safe;
  }

  /**
   * Escape a string for use in JavaScript source code.
   * @param {string} str - String to escape
   * @returns {string} Escaped string
   */
  _escapeString(str) {
    if (!str) return '';
    return str
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r');
  }
}

export {  TestGenerator  };
